name: ${project.name}
version: ${project.version}
main: com.lenis0012.bukkit.marriage2.internal.MarriagePlugin
authors: [ lenis0012, DraimGooSe ]
description: Плагин, который предоставляет функцию для начала отношений в minecraft.
website: https://github.com/DraimCiDo/Marriage/
softdepend: [Vault, PlotSquared]
api-version: '1.13'
commands:
  marry:
    description: Основная команда.
    usage: /marry <args>
