name: ${project.name}
version: ${project.version}
main: com.lenis0012.bukkit.marriage2.internal.MarriagePlugin
authors: [ DraimGooSe, lenis0012 ]
description: Плагин, который предоставляет функцию для начала отношений в MineCraft.
website: https://github.com/DraimDEV/Marriage/
softdepend: [Vault, PlotSquared]
api-version: '1.13'
commands:
  marry:
    description: Основная команда.
    usage: /marry <args>
